### ISSUE TITLE
Include separate breakpoints file

### ISSUE THREAD

**Issue by johnfraney** [angeal185/bootstrap-4-stylus#1]
Currently breakpoints are all hard-coded into files (see [container.styl](https://github.com/angeal185/bootstrap-4-stylus/blob/master/includes/container.styl)). Having separate breakpoint variables ([like Bootstrap does](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L140)) would make this library more extensible.

(Thanks for putting the work in to convert this, by the way!)

**Comment by angeal185** [comment]
I added the vars you requested and a few more to the index.style file in the root dir. I will increase the list to include similar converts of many of the ones that bootstrap uses in the next release.

**Comment by johnfraney** [comment]
@angeal185 Whew, quick turnaround. Thanks again!

**Comment by angeal185** [comment]
no problems. it was a good idea. new vars are being added to the v1.0.2 branch as i go through them. when they are done, v1.0.2 will be merged into the master.
