### ISSUE TITLE
I don't see grid inside the includes

### ISSUE THREAD

**Issue by Gcamara14** [angeal185/bootstrap-4-stylus#10]
I don't see this being an exact port of the bootstrap 4 sass version. Naming convention is a bit off, but not all the stylus files are in.

Missing the navbar.styl and the grid.styl, etc

**Comment by angeal185** [comment]
The description reads that this is a port of bootstrap 4 to stylus, not a port of bootstrap 4 sass to stylus. The navbar is in nav.styl and the grid is broken down into its respective parts. For example, row is in row.styl, col is in col.styl  and so on.
