### ISSUE TITLE
broken string for hamburger menu svg

### ISSUE THREAD

**Issue by StevenRadig** [angeal185/bootstrap-4-stylus#11]
lines 334 and 362 of /includes/nav.styl have incorrect strings for the hamburger icon svgs

(is) data:image/svg+xml
(should be) data:image/svg+xml;
The difference? semicolon after xml

(is) xmlns='http //www.w3.org/2000/svg
(should be) xmlns='http://www.w3.org/2000/svg
The difference? colon between http and //

**Comment by angeal185** [comment]
nice catch, even the original bootstrap css is missing that semicolon after xml;. the issue has been fixed in v1.0.6.
