### ISSUE TITLE
Is this still based on Bootstrap 3?

### ISSUE THREAD

**Issue by mblackritter** [angeal185/bootstrap-4-stylus#15]
I couldn't find which version of Bootstrap this is based on.

Having a look on the resulting ```bootstrap.css``` and comparing that to the more than 10000 lines of the current [Bootstrap 4.3.1](https://unpkg.com/bootstrap@4.3.1/dist/css/bootstrap.css), after expanding it via the Sublime CSS Formater plugin, the 7760 lines of the resulting CSS from Boostrap 4 Stylus seem way off from that and also classes like ```order-first``` are missing.

So I assume this is still based on Bootstrap 3? 🤔

**Comment by angeal185** [comment]
this was never based on bootstrap 3 so your assumption is off. the compile output order does not mimic bootstrap 4 so that might account for the difference. if you find any issues feel free to do something constructive like contribute by making a pull request.
