### ISSUE TITLE
Nib?

### ISSUE THREAD

**Issue by rbtsolis** [angeal185/bootstrap-4-stylus#7]
Hi, i saw the code, and i think, it's better if we use nib, what do you think about that? i think it's better because we can write only one line and nib automatically add the prefix

**Comment by angeal185** [comment]
Not sure everyone would appreciate that. It would require everyone to learn nib. It would also add nib and stylus as local dependencies when currently there are no local dependencies. Even the npm module has no local dependencies and only uses the globally installed stylus module as a dependency, which most who use stylus would already have installed.
