### ISSUE TITLE
There are errors when I import using gulp-stylus

### ISSUE THREAD

**Issue by duduindo** [angeal185/bootstrap-4-stylus#8]
### Lines
* https://github.com/angeal185/bootstrap-4-stylus/blob/052d6c698d2c938c1b2321bdca53bc6f3d84119b/includes/carousel.styl#L87-L88
* https://github.com/angeal185/bootstrap-4-stylus/blob/052d6c698d2c938c1b2321bdca53bc6f3d84119b/includes/carousel.styl#L91-L92
* https://github.com/angeal185/bootstrap-4-stylus/blob/052d6c698d2c938c1b2321bdca53bc6f3d84119b/includes/custom.styl#L53-L54
* https://github.com/angeal185/bootstrap-4-stylus/blob/052d6c698d2c938c1b2321bdca53bc6f3d84119b/includes/custom.styl#L58-L59
* https://github.com/angeal185/bootstrap-4-stylus/blob/052d6c698d2c938c1b2321bdca53bc6f3d84119b/includes/custom.styl#L67-L68
* https://github.com/angeal185/bootstrap-4-stylus/blob/052d6c698d2c938c1b2321bdca53bc6f3d84119b/includes/custom.styl#L88-L89
* https://github.com/angeal185/bootstrap-4-stylus/blob/052d6c698d2c938c1b2321bdca53bc6f3d84119b/includes/nav.styl#L334-L335
* https://github.com/angeal185/bootstrap-4-stylus/blob/052d6c698d2c938c1b2321bdca53bc6f3d84119b/includes/nav.styl#L363-L364

### How I import
```sass
@import 'bootstrap-4-stylus/includes/*.styl'
```
My temporary solution   
```sass
@import 'bootstrap-4-stylus/includes/!(carousel|custom|nav)*.styl'
```

**Comment by angeal185** [comment]
good catch. i just released v1.0.5  with this line break issue resolved. issue closed.
